# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(918, 384)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.tabWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 881, 371))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tabWidget.setFont(font)
        self.tabWidget.setIconSize(QtCore.QSize(16, 16))
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.backup_process_bar = QtWidgets.QProgressBar(self.tab)
        self.backup_process_bar.setGeometry(QtCore.QRect(50, 100, 831, 23))
        self.backup_process_bar.setProperty("value", 50)
        self.backup_process_bar.setObjectName("backup_process_bar")
        self.backup_detail_text = QtWidgets.QTextBrowser(self.tab)
        self.backup_detail_text.setGeometry(QtCore.QRect(50, 140, 791, 192))
        self.backup_detail_text.setObjectName("backup_detail_text")
        self.backup_path_text = QtWidgets.QTextBrowser(self.tab)
        self.backup_path_text.setGeometry(QtCore.QRect(50, 50, 691, 31))
        self.backup_path_text.setObjectName("backup_path_text")
        self.lb1_chose_btn_one = QtWidgets.QPushButton(self.tab)
        self.lb1_chose_btn_one.setGeometry(QtCore.QRect(760, 10, 75, 31))
        self.lb1_chose_btn_one.setObjectName("lb1_chose_btn_one")
        self.label = QtWidgets.QLabel(self.tab)
        self.label.setGeometry(QtCore.QRect(50, 10, 700, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.lb1_chose_btn_two = QtWidgets.QPushButton(self.tab)
        self.lb1_chose_btn_two.setGeometry(QtCore.QRect(760, 50, 75, 31))
        self.lb1_chose_btn_two.setObjectName("lb1_chose_btn_two")
        self.backup_process_bar.raise_()
        self.backup_detail_text.raise_()
        self.backup_path_text.raise_()
        self.label.raise_()
        self.lb1_chose_btn_one.raise_()
        self.lb1_chose_btn_two.raise_()
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.import_detail_text = QtWidgets.QTextBrowser(self.tab_2)
        self.import_detail_text.setGeometry(QtCore.QRect(50, 140, 791, 192))
        self.import_detail_text.setObjectName("import_detail_text")
        self.import_process_bar = QtWidgets.QProgressBar(self.tab_2)
        self.import_process_bar.setGeometry(QtCore.QRect(50, 100, 831, 23))
        self.import_process_bar.setProperty("value", 24)
        self.import_process_bar.setObjectName("import_process_bar")
        self.import_path_text = QtWidgets.QTextBrowser(self.tab_2)
        self.import_path_text.setGeometry(QtCore.QRect(50, 50, 691, 31))
        self.import_path_text.setObjectName("import_path_text")
        self.lb2_chose_btn_one = QtWidgets.QPushButton(self.tab_2)
        self.lb2_chose_btn_one.setGeometry(QtCore.QRect(760, 10, 75, 31))
        self.lb2_chose_btn_one.setObjectName("lb2_chose_btn_one")
        self.label_2 = QtWidgets.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(50, 10, 700, 30))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.lb2_chose_btn_two = QtWidgets.QPushButton(self.tab_2)
        self.lb2_chose_btn_two.setGeometry(QtCore.QRect(760, 50, 75, 31))
        self.lb2_chose_btn_two.setObjectName("lb2_chose_btn_two")
        self.import_detail_text.raise_()
        self.import_process_bar.raise_()
        self.import_path_text.raise_()
        self.label_2.raise_()
        self.lb2_chose_btn_one.raise_()
        self.lb2_chose_btn_two.raise_()
        self.tabWidget.addTab(self.tab_2, "")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lb1_chose_btn_one.setText(_translate("MainWindow", "PushButton"))
        self.label.setText(_translate("MainWindow", "Choose the fold path of /\'World of Warcraft/_retail_\'"))
        self.lb1_chose_btn_two.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "BackUp"))
        self.lb2_chose_btn_one.setText(_translate("MainWindow", "PushButton"))
        self.label_2.setText(_translate("MainWindow", "Choose the fold path of /\'World of Warcraft/_retail_\'"))
        self.lb2_chose_btn_two.setText(_translate("MainWindow", "PushButton"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Import"))

