# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1024, 523)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(1024, 0))
        MainWindow.setMaximumSize(QtCore.QSize(1024, 540))
        icon = QtGui.QIcon.fromTheme(":/icon/src/icon/wow.png")
        MainWindow.setWindowIcon(icon)
        self.main_win = QtWidgets.QWidget(MainWindow)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.main_win.sizePolicy().hasHeightForWidth())
        self.main_win.setSizePolicy(sizePolicy)
        self.main_win.setMinimumSize(QtCore.QSize(1024, 505))
        self.main_win.setMaximumSize(QtCore.QSize(1024, 520))
        self.main_win.setMouseTracking(False)
        self.main_win.setObjectName("main_win")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.main_win)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 981, 481))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSizeConstraint(QtWidgets.QLayout.SetDefaultConstraint)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tab_ctr = QtWidgets.QTabWidget(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.tab_ctr.setFont(font)
        self.tab_ctr.setIconSize(QtCore.QSize(16, 16))
        self.tab_ctr.setObjectName("tab_ctr")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.tab)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(10, 0, 951, 431))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.vl_1_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.vl_1_1.setContentsMargins(0, 0, 0, 0)
        self.vl_1_1.setSpacing(0)
        self.vl_1_1.setObjectName("vl_1_1")
        self.groupBox = QtWidgets.QGroupBox(self.verticalLayoutWidget_2)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayoutWidget_3 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_3.setGeometry(QtCore.QRect(770, 70, 151, 121))
        self.verticalLayoutWidget_3.setObjectName("verticalLayoutWidget_3")
        self.vl_1_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_3)
        self.vl_1_2.setContentsMargins(0, 0, 0, 0)
        self.vl_1_2.setObjectName("vl_1_2")
        self.lb1_chose_btn_one = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.lb1_chose_btn_one.setObjectName("lb1_chose_btn_one")
        self.vl_1_2.addWidget(self.lb1_chose_btn_one)
        self.lb1_chose_btn_two = QtWidgets.QPushButton(self.verticalLayoutWidget_3)
        self.lb1_chose_btn_two.setObjectName("lb1_chose_btn_two")
        self.vl_1_2.addWidget(self.lb1_chose_btn_two)
        self.verticalLayoutWidget_4 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_4.setGeometry(QtCore.QRect(50, 40, 691, 41))
        self.verticalLayoutWidget_4.setObjectName("verticalLayoutWidget_4")
        self.vl_1_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_4)
        self.vl_1_3.setContentsMargins(0, 0, 0, 0)
        self.vl_1_3.setObjectName("vl_1_3")
        self.label = QtWidgets.QLabel(self.verticalLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.vl_1_3.addWidget(self.label)
        self.verticalLayoutWidget_5 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_5.setGeometry(QtCore.QRect(49, 89, 691, 94))
        self.verticalLayoutWidget_5.setObjectName("verticalLayoutWidget_5")
        self.vl_1_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_5)
        self.vl_1_4.setContentsMargins(0, 0, 0, 0)
        self.vl_1_4.setObjectName("vl_1_4")
        self.backup_path_text = QtWidgets.QTextBrowser(self.verticalLayoutWidget_5)
        self.backup_path_text.setObjectName("backup_path_text")
        self.vl_1_4.addWidget(self.backup_path_text)
        self.verticalLayoutWidget_6 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_6.setGeometry(QtCore.QRect(49, 190, 881, 80))
        self.verticalLayoutWidget_6.setObjectName("verticalLayoutWidget_6")
        self.vl_1_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_6)
        self.vl_1_5.setContentsMargins(0, 0, 0, 0)
        self.vl_1_5.setObjectName("vl_1_5")
        self.backup_process_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget_6)
        self.backup_process_bar.setProperty("value", 50)
        self.backup_process_bar.setObjectName("backup_process_bar")
        self.vl_1_5.addWidget(self.backup_process_bar)
        self.verticalLayoutWidget_7 = QtWidgets.QWidget(self.groupBox)
        self.verticalLayoutWidget_7.setGeometry(QtCore.QRect(50, 280, 881, 141))
        self.verticalLayoutWidget_7.setObjectName("verticalLayoutWidget_7")
        self.vl_1_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_7)
        self.vl_1_6.setContentsMargins(0, 0, 0, 0)
        self.vl_1_6.setObjectName("vl_1_6")
        self.backup_detail_text = QtWidgets.QTextBrowser(self.verticalLayoutWidget_7)
        self.backup_detail_text.setObjectName("backup_detail_text")
        self.vl_1_6.addWidget(self.backup_detail_text)
        self.vl_1_1.addWidget(self.groupBox)
        self.tab_ctr.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.verticalLayoutWidget_15 = QtWidgets.QWidget(self.tab_2)
        self.verticalLayoutWidget_15.setGeometry(QtCore.QRect(10, 0, 951, 431))
        self.verticalLayoutWidget_15.setObjectName("verticalLayoutWidget_15")
        self.vl_2_1 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_15)
        self.vl_2_1.setContentsMargins(0, 0, 0, 0)
        self.vl_2_1.setObjectName("vl_2_1")
        self.groupBox_3 = QtWidgets.QGroupBox(self.verticalLayoutWidget_15)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayoutWidget_16 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_16.setGeometry(QtCore.QRect(770, 70, 151, 121))
        self.verticalLayoutWidget_16.setObjectName("verticalLayoutWidget_16")
        self.vl_2_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_16)
        self.vl_2_2.setContentsMargins(0, 0, 0, 0)
        self.vl_2_2.setObjectName("vl_2_2")
        self.lb2_chose_btn_one = QtWidgets.QPushButton(self.verticalLayoutWidget_16)
        self.lb2_chose_btn_one.setObjectName("lb2_chose_btn_one")
        self.vl_2_2.addWidget(self.lb2_chose_btn_one)
        self.lb2_chose_btn_two = QtWidgets.QPushButton(self.verticalLayoutWidget_16)
        self.lb2_chose_btn_two.setObjectName("lb2_chose_btn_two")
        self.vl_2_2.addWidget(self.lb2_chose_btn_two)
        self.verticalLayoutWidget_17 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_17.setGeometry(QtCore.QRect(50, 40, 691, 41))
        self.verticalLayoutWidget_17.setObjectName("verticalLayoutWidget_17")
        self.vl_2_3 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_17)
        self.vl_2_3.setContentsMargins(0, 0, 0, 0)
        self.vl_2_3.setObjectName("vl_2_3")
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_17)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.vl_2_3.addWidget(self.label_11)
        self.verticalLayoutWidget_18 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_18.setGeometry(QtCore.QRect(49, 89, 691, 94))
        self.verticalLayoutWidget_18.setObjectName("verticalLayoutWidget_18")
        self.vl_2_4 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_18)
        self.vl_2_4.setContentsMargins(0, 0, 0, 0)
        self.vl_2_4.setObjectName("vl_2_4")
        self.import_path_text = QtWidgets.QTextBrowser(self.verticalLayoutWidget_18)
        self.import_path_text.setObjectName("import_path_text")
        self.vl_2_4.addWidget(self.import_path_text)
        self.verticalLayoutWidget_19 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_19.setGeometry(QtCore.QRect(49, 190, 881, 80))
        self.verticalLayoutWidget_19.setObjectName("verticalLayoutWidget_19")
        self.vl_2_5 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_19)
        self.vl_2_5.setContentsMargins(0, 0, 0, 0)
        self.vl_2_5.setObjectName("vl_2_5")
        self.import_process_bar = QtWidgets.QProgressBar(self.verticalLayoutWidget_19)
        self.import_process_bar.setProperty("value", 50)
        self.import_process_bar.setObjectName("import_process_bar")
        self.vl_2_5.addWidget(self.import_process_bar)
        self.verticalLayoutWidget_20 = QtWidgets.QWidget(self.groupBox_3)
        self.verticalLayoutWidget_20.setGeometry(QtCore.QRect(50, 280, 881, 141))
        self.verticalLayoutWidget_20.setObjectName("verticalLayoutWidget_20")
        self.vl_2_6 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_20)
        self.vl_2_6.setContentsMargins(0, 0, 0, 0)
        self.vl_2_6.setObjectName("vl_2_6")
        self.import_detail_text = QtWidgets.QTextBrowser(self.verticalLayoutWidget_20)
        self.import_detail_text.setObjectName("import_detail_text")
        self.vl_2_6.addWidget(self.import_detail_text)
        self.vl_2_1.addWidget(self.groupBox_3)
        self.tab_ctr.addTab(self.tab_2, "")
        self.verticalLayout.addWidget(self.tab_ctr)
        MainWindow.setCentralWidget(self.main_win)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tab_ctr.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "WOW addons helper"))
        self.groupBox.setTitle(_translate("MainWindow", "Backup your addons"))
        self.lb1_chose_btn_one.setText(_translate("MainWindow", "Path"))
        self.lb1_chose_btn_two.setText(_translate("MainWindow", "Backup"))
        self.label.setText(_translate("MainWindow", "Choose the fold path of /\'World of Warcraft/_retail_\'  for backup"))
        self.tab_ctr.setTabText(self.tab_ctr.indexOf(self.tab), _translate("MainWindow", "BackUp"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Import your addons"))
        self.lb2_chose_btn_one.setText(_translate("MainWindow", "Path"))
        self.lb2_chose_btn_two.setText(_translate("MainWindow", "Import"))
        self.label_11.setText(_translate("MainWindow", "Choose the fold path of /\'World of Warcraft/_retail_\'  for import"))
        self.tab_ctr.setTabText(self.tab_ctr.indexOf(self.tab_2), _translate("MainWindow", "Import"))

import res_rc
